### ISSUE TITLE
read_bvals_bvecs can't read double volume dwi

### ISSUE THREAD

**Issue by soichih** [dipy/dipy#2601] opened 2022-05-27 22:11 UTC
This is a comically similar issue to the one I've reported in https://github.com/dipy/dipy/issues/2046

Jan Jurzawski tried to upload b0 only dwi volume on brainlife and it failed with this error message.

```
validation failed OSError: b-values and b-vectors shapes do not correspond
```

He had

bvecs

```
0.000 0.000
0.000 0.000
0.000 0.000
```

bvals

```
0 0
```

The above error message is from dipy 1.3.0, btw. With dipy 1.5.0,  I ran into this

```
bvals and bvecs should be (N,) and (N, 3) arrays respectively, where N is the number of diffusion gradients
... failed to parse bvals/bvecs.. trying with atol=1
Traceback (most recent call last):
  File "./validate.py", line 154, in <module>
    gtab = gradient_table(bvals, bvecs)
  File "/home/hayashis/.local/lib/python3.8/site-packages/dipy/core/gradients.py", line 599, in gradient_table
    return gradient_table_from_bvals_bvecs(bvals, bvecs, big_delta=big_delta,
  File "/home/hayashis/.local/lib/python3.8/site-packages/dipy/core/gradients.py", line 287, in gradient_table_from_bvals_bvecs
    raise ValueError("bvals and bvecs should be (N,) and (N, 3) arrays "
ValueError: bvals and bvecs should be (N,) and (N, 3) arrays respectively, where N is the number of diffusion gradients

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./validate.py", line 160, in <module>
    gtab = gradient_table(bvals, bvecs, atol=1)
  File "/home/hayashis/.local/lib/python3.8/site-packages/dipy/core/gradients.py", line 599, in gradient_table
    return gradient_table_from_bvals_bvecs(bvals, bvecs, big_delta=big_delta,
  File "/home/hayashis/.local/lib/python3.8/site-packages/dipy/core/gradients.py", line 287, in gradient_table_from_bvals_bvecs
    raise ValueError("bvals and bvecs should be (N,) and (N, 3) arrays "
ValueError: bvals and bvecs should be (N,) and (N, 3) arrays respectively, where N is the number of diffusion gradients

```

Is the bvals/bvecs we are uploading indeed "invalid"?

**Comment by skoudoro** [comment] 2022-05-27 22:16
I feel like he just needs to transpose his bvecs and it should work.

**Comment by skoudoro** [comment] 2022-05-27 22:21
Strange, we should handle this case normally and from what I see in the code, let me test...

**Comment by skoudoro** [comment] 2022-05-27 22:26
I can not reproduce your error. Can you share your file and code? I am using DIPY 1.50

**Comment by jk619** [comment] 2022-05-27 23:06
[bvec_bval.zip](https://github.com/dipy/dipy/files/8790038/bvec_bval.zip).

`>>> bvec,bvals = read_bvals_bvecs('dti_blip_down.bval','dti_blip_down.bvec')
>>> bvec
array([0., 0.])
>>> bvals
array([[0., 0., 0.],
       [0., 0., 0.]])`

The bvecs file is exactly as Soichi pasted so it seems Dipy takes the transpose?

**Comment by arokem** [comment] 2022-05-28 02:53
I am getting: 

```
In [2]: from dipy.io.gradients import read_bvals_bvecs

In [3]: read_bvals_bvecs("./bvec_bval/dti_blip_down.bval", "./bvec_bval/dti_blip
   ...: _down.bvec")
Out[3]: 
(array([0., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))
```

Seems like everything is working as expected. What's the issue?

**Comment by skoudoro** [comment] 2022-05-30 14:48
Hi @soichih and @jk619,

Do you have an update on this? should we close this issue?  Neither I nor Ariel could reproduce your error with your bvec_bval file. It is handled correctly,  So I am not sure what we can do. 

Thanks in advance for the feedback

**Comment by soichih** [comment] 2022-05-30 15:09
Hi @skoudoro I am on a break this week, but I can try to look into this next week. Which version of dipy are you testing it on? Also, when you load bcecs/bvals are you trimming/stripping the input files? I might have some extra white space/newline at the end of files.

**Comment by arokem** [comment] 2022-06-01 05:31
I'm testing this on master. I haven't touched the data before running the code.

**Comment by skoudoro** [comment] 2023-12-29 23:28
Closing this since we can not reproduce the issue and seems to work as expected.

feel free to reopen it @jk619 or @soichih

**Closed by skoudoro** 2023-12-29 23:28 UTC
Labels: :grey_question: type:Question :grey_question:, state: needs feedback
