### ISSUE TITLE
Importing an example in another example - doc

### ISSUE THREAD

**Issue by BramshQamar** [dipy/dipy#2537] opened 2022-02-25 02:19 UTC
https://github.com/dipy/dipy/blob/79e96058e9fe30a587d0342c61c59bf9d3f37bea/doc/examples/streamline_registration.py#L33

Should it be changed from `from streamline_tools import *` to  `from doc.examples.streamline_tools import *`?

If the **streamline_tools.py** example has not been run before, the current way of importing gives me an error.

**Comment by arokem** [comment] 2022-02-25 02:27
Are you running it from the doc/examples directory?

You have to run it from there so that this import works. Maybe we need to
document that somewhere.

**Comment by BramshQamar** [comment] 2022-02-25 02:36
> Are you running it from the doc/examples directory? You have to run it from there so that this import works. Maybe we need to document that somewhere.
> […](#)


Hi @arokem, 

I ran it in a python notebook and did not run the streamline_tools.py file from inside the doc/examples folder.

I just copy-pasted this import command:
`from streamline_tools import * `
It gives an error but works when I import it like this
`from doc.examples.streamline_tools import *`

**Comment by arokem** [comment] 2022-02-25 02:39
That’s surprising! I wouldn’t expect to be able to import from within the
docs directory, because it’s not a python package. You learn something we
every day :-)

**Comment by skoudoro** [comment] 2022-02-25 05:48
This is a duplicate of #2400.

We said we should split them to be independent tutorials, this is on a to-do list. 

Since this is the 2nd-3rd time that you encounter this problem, it would be great if you could start a PR to split these 2 tutorials. I think you start to have a lot of experience with those 2 examples and it will help a lot the community to clarify them. We will be happy to help you during this process.

**Comment by Sujal3013** [comment] 2023-02-27 06:54
Hello ,I wish to contribute to the project and I consider this issue to be suitable to be resolved by me.
If possible you may assign this issue to me.

**Closed** 2023-04-23 14:18 UTC
Labels: type:Bug Fix, type:Maintenance
