### ISSUE TITLE
load_nifti import doesn't work if using submodule directly

### ISSUE THREAD

**Issue by sreekarchigurupati** [dipy/dipy#3020] opened 2023-12-21 19:03 UTC
## Description
`img, _ = dipy.io.image.load_nifti("...")`
doesn't work
but using
```
from dipy.io.image import load_nifti
img, _ = load_nifti("...") 
```
works

## Way to reproduce
Operating System : Linux-6.2.0-39-generic-x86_64-with-glibc2.35
Python version: Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
dipy version: 1.7.0
NumPy 1.26.1
SciPy 1.8.0
Nibabel 5.1.0
H5py 3.6.0
CVXPY not installed
fury 0.9.0

**Comment by sreekarchigurupati** [comment] 2023-12-21 19:06
Returns
`AttributeError: module 'dipy' has no attribute 'io'`

**Comment by skoudoro** [comment] 2023-12-28 02:27
Hi @sreekarchigurupati,

This is an expected behavior.

when you do `import dipy` we do not import submodules. We prefer the user to do explicit import instead of implicit import. Furthermore, this avoid to import module that you do not use and "save memory". 

so closing for now. 

Feel free to open the debate in a discussion if you would like another behavior.

**Closed by skoudoro** 2023-12-28 02:27 UTC

**Comment by skoudoro** [comment] 2023-12-28 02:28
Also, that's why all our tutorial never use `import dipy` only.

**Comment by gsamanidharreddy** [comment] 2024-01-05 07:56
Hello @sreekarchigurupati 

dipy.io.image.load_nifti, might not work because the function load_nifti is not directly accessible from the dipy.io.image namespace.

So, generally better to import functions and classes directly from the modules to make the code more readable and avoid potential naming conflicts.
