### ISSUE TITLE
Dipy Segmentation Core Dumped - Windows.Record

### ISSUE THREAD

**Issue by QueenofSumer** [dipy/dipy#2745] opened 2023-03-13 20:03 UTC
## Description
When going through the Connectivity Matrices, ROI Intersections and Density Maps tutorial (https://dipy.org/documentation/1.6.0./examples_built/streamline_tools/#example-streamline-tools)
I am running into an issue when running the following line: 
```
window.record(scene, n_frames=1, out_path='corpuscallosum_axial.png',
              size=(800, 800))
Segmentation fault (core dumped)
``` 

## Way to reproduce
- [ ] Here is the code that first raised the issue ( copied from https://dipy.org/documentation/1.6.0./examples_built/streamline_tools/#example-streamline-tools).
- [ ] Operating system and version: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
- [ ] Python version: 3.9.7
- [ ] dipy version: 1.6.0
- [ ] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__) 1.21.2
    * import scipy; print("SciPy", scipy.__version__): 1.7.3
    * import nibabel; print("Nibabel", nibabel.__version__): 3.2.2
    * import h5py; print("H5py", h5py.__version__): 3.8.0
    * import cvxpy; print("Cvxpy", cvxpy.__version__)
    * import fury; print("fury", fury.__version__): 0.8.0

**Comment by kev1nzh37** [comment] 2023-03-15 04:29
Hi, I also encountered this error. How did you solve it?

**Comment by pjsjongsung** [comment] 2023-03-15 05:45
I replicated the error, but the error only occured on Ubuntu when not using GUI. Was the machine operated through terminal with no GUI @QueenofSumer @kev1nzh37 ? I believe it might be related to how the scene first loads the window to capture, which can create an error if the system is not capable of loading a visual window at the first place.

**Comment by arokem** [comment] 2023-03-15 14:15
I will also add that this is the kind of scenario where XVFB and [xvfbwrapper](https://pypi.org/project/xvfbwrapper/) may be useful. Could you try installing it and running your code like this?

```
from xvfbwrapper import Xvfb

vdisplay = Xvfb()
vdisplay.start()

# your code

vdisplay.stop()
```

**Comment by kev1nzh37** [comment] 2023-03-16 02:38
Thank you, guys. I have resolved this problem. The environment is Docker.

**Comment by arokem** [comment] 2023-03-16 02:41
@kev1nzh37 : did xvfbwrapper do the trick for you? @QueenofSumer : did this resolve your issue as well? Can we close this issue?

**Comment by kev1nzh37** [comment] 2023-03-16 03:21
@arokem Yes, maybe the problem is with my local environment. Please close this issue. Thank you again.

**Closed** 2023-03-16 11:31 UTC
