### ISSUE TITLE
strange tracks

### ISSUE THREAD

**Issue by salma1601** [dipy/dipy#1354] opened 2017-10-10 16:14 UTC
Hi dipy experts,

I am using a tracking pipeline completely relying on dipy: denoising-dti tensor fitting-CSD reconstruction-deterministic Eudx tracking. However, the tracks of half of my subjects are weird while the other half is OK.
Investigating more carefully the problem, I noticed that the estimated response with `reconst.csdeconv.recursive_response` was bad for these subjects, but I can't figure out why and how to fix the issue.
Here are the responses
![csd_recursive_response128](https://user-images.githubusercontent.com/7080143/31396836-bd18a842-ade4-11e7-93d0-5388c4e5b450.png)![csd_recursive_response129](https://user-images.githubusercontent.com/7080143/31396863-c8b9b678-ade4-11e7-87f1-4a5eaf78bf2a.png)
 and the tracks
https://user-images.githubusercontent.com/7080143/31396985-12562398-ade5-11e7-812b-501e6a579750.png
https://user-images.githubusercontent.com/7080143/31397042-37dc6f5a-ade5-11e7-8aab-fe20b284f445.png

Have anyone experienced such a problem ?

Many thanks,
Salma

**Comment by skoudoro** [comment] 2020-09-09 21:18
Hi @salma1601,

I believe that your CSD response issue has been solved by #2191. Since we can not reproduce this old problem, I will close the issue for now. Feel free to reopen it!

**Closed by skoudoro** 2020-09-09 21:18 UTC
Labels: :grey_question: type:Question :grey_question:
