### ISSUE TITLE
DKI metrics' accuracy

### ISSUE THREAD

**Issue by rosella1234** [dipy/dipy#2274] opened 2020-10-29 08:26 UTC
## Description
[Please provide a general introduction to the issue/proposal.]

[If reporting a bug, attach the entire traceback from Python and follow the way to reproduce below]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [x] Relevant images (if any)
- [ ] Operating system and version (run `python -c "import platform; print(platform.platform())"`)
- [ ] Python version (run `python -c "import sys; print("Python", sys.version)"`)
- [ ] dipy version (run `python -c "import dipy; print(dipy.__version__)"`)
- [ ] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__)
    * import scipy; print("SciPy", scipy.__version__)
    * import nibabel; print("Nibabel", nibabel.__version__)
    * import h5py; print("H5py", h5py.__version__)
    * import cvxpy; print("Cvxpy", cvxpy.__version__)
    * import fury; print("fury", fury.__version__)

**Comment by rosella1234** [comment] 2020-10-29 08:34
Hi
I have some doubts about computation of DKI measures on neonatal spinal cord imaging. My initial DKI image's quality is not extremely high due to short acquisition time necessary for my patients' age range. Acquisition sequence is made up of 6 b=0, 13 b=700 and 13 b=2100 s/mm2. I put as a input of dipy script the DKI image after FOV reduction and motion correction. I then perform Gaussian smoothing with fwhm=1.25 as provided in the example use of dipy , and constraint DKI measures between 0 and 3. However, my metrics have black holes and do not seem really accurate or informative. Is this due only to image acquisition setting or to somthing in my processing pipeline? 
Please find attached my script, my DKI measures and the DKI image in input for dipy.
  
[MK.nii.gz](https://github.com/dipy/dipy/files/5457015/MK.nii.gz)
[KFA.nii.gz](https://github.com/dipy/dipy/files/5457016/KFA.nii.gz)
[kurtosis_crop_moco.nii.gz](https://github.com/dipy/dipy/files/5457018/kurtosis_crop_moco.nii.gz)
Thank you,
rosella

**Comment by skoudoro** [comment] 2020-10-29 19:05
Hi @rosella1234,

Thank you for your feedback, we will look into it.

Also, @arokem and @RafaelNH can you have deeper a look? We might have a problem or we need to be more specific with the expected input data. Here some similar/duplicate issue:  #2164 and #2026

**Comment by arokem** [comment] 2020-10-29 19:28
Hi Rosella! Thanks for getting in touch. Do you do any denoising/smoothing
of the data before fitting DKI? If you are going to smooth the results
anyway, I would recommend trying to do that before fitting.

**Comment by rosella1234** [comment] 2020-10-30 08:15
Hi, thanks for your response! Before the fitting I correct the data for motion correction inside Spinal Cord Toolbox (https://sourceforge.net/projects/spinalcordtoolbox/), give this motion corrected image as a input of dipy, and here perform Gaussian smoothing before fitting to Kurtosis Model.

**Comment by skoudoro** [comment] 2021-03-24 15:17
duplicate of #2311. Closing

**Closed by skoudoro** 2021-03-24 15:17 UTC
Labels: type:Bug Fix, type:Enhancement
